# Generated by Django 2.1.5 on 2019-01-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='author',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='lookup',
            field=models.IntegerField(default=0),
        ),
    ]
