# Generated by Django 2.1.5 on 2019-01-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20190128_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='post_type',
            field=models.CharField(default='question', max_length=125),
        ),
    ]
