# Generated by Django 2.1.5 on 2019-01-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_board_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(default='default', max_length=125),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='default', max_length=125),
        ),
    ]
