# Generated by Django 2.1.5 on 2019-01-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20190129_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('Steering', 'Steering'), ('Brake', 'Brake'), ('Engine & Fuel', 'Engine & Fuel'), ('Mecca', 'Mecca'), ('Display', 'Display'), ('Motor Dynamometer', 'Motor Dynamometer'), ('Simulator', 'Simulator'), ('Electric Vehicle', 'Electric Vehicle')], max_length=125),
        ),
    ]
