# Generated by Django 2.1.5 on 2019-01-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20190129_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('0', 'default'), ('1', 'C-EPS/ABS/ESC'), ('2', 'R-EPS/EOL'), ('3', 'EHPS/iMEB'), ('4', 'Brake Booster'), ('5', 'EOL Caliper')], max_length=125),
        ),
    ]
