# Generated by Django 2.1.5 on 2019-02-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20190129_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
