# Generated by Django 2.1.5 on 2019-02-12 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_delete_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_detail_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_type', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=125)),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product_detail_type')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='kind',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product_type'),
        ),
    ]
