# Generated by Django 2.1.5 on 2019-02-12 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20190212_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product_type',
            name='detail_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_detail_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product_detail_type'),
        ),
        migrations.AddField(
            model_name='product_detail_type',
            name='product_type',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product_type'),
            preserve_default=False,
        ),
    ]
