# Generated by Django 2.1.5 on 2019-02-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20190212_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_detail_type',
        ),
        migrations.RemoveField(
            model_name='product_detail_type',
            name='product_type',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Product_detail_type',
        ),
        migrations.DeleteModel(
            name='Product_type',
        ),
    ]
