# Generated by Django 2.1.5 on 2019-02-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('post_type', models.CharField(default='question', max_length=125)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=125, null=True)),
                ('password', models.CharField(max_length=15)),
                ('lookup', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
