# Generated by Django 2.1.5 on 2019-03-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_comments_posttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='posttime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
    ]
