# Generated by Django 2.1.5 on 2019-02-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='hire_type',
            field=models.CharField(choices=[('intern', 'intern'), ('employee', 'employee')], max_length=125),
        ),
    ]
