# Generated by Django 2.1.5 on 2019-02-02 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0002_auto_20190202_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=125, null=True)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=125, null=True)),
                ('e_mail', models.CharField(blank=True, max_length=125, null=True)),
                ('address', models.CharField(blank=True, max_length=125, null=True)),
                ('college', models.CharField(blank=True, max_length=125, null=True)),
                ('major', models.CharField(blank=True, max_length=125, null=True)),
                ('graduate', models.BooleanField(default=False)),
                ('document', models.FileField(null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apply.Hire')),
            ],
        ),
    ]
